name: Backend - Main - Release on push

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  java-version: 21
  distribution: graalvm
  node-js-version: 20.x
  author-name: Marc Scheib
  author-email: marc.scheib@cycrilabs.com

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js [${{ env.node-js-version }}]
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-js-version }}

      - name: Release
        run: npm exec --package=@semantic-release/changelog --package=@semantic-release/git --package=@semantic-release/exec --yes -- semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ env.author-name }}
          GIT_AUTHOR_EMAIL: ${{ env.author-email }}

  publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.head_ref || github.ref_name }}]
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Retrieve tag
        run: |
          echo "TAG=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT
        id: version

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/cycrilabs/keycloak:${{ steps.version.outputs.TAG }}
